name: RandomTreasure
version: '1'
main: randomtreasure.randomtreasure.RandomTreasure
api-version: 1.19
authors: [ SakakiAruka ]
description: place chets, can get random items.
website: https://github.com/Sakaki-Aruka
commands:
  randomtreasureconfigreload:
    permission: treasure.op